### ISSUE TITLE
[Bug]: Updating the Buymeacoffee links

### ISSUE THREAD

**Issue by Sonichigo** [kaiwalyakoparkar/node-js-project-template#1]
### Describe the bug

Convert https://buymecoffee.com/kaiwalya to https://buymeacoffee.com/kaiwalya

### Expected Behavior

Correct Link: https://buymeacoffee.com/kaiwalya

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for reporting, Fixed :+1:
